project_id = "puwbmjzbkfzhaqtaxnti"

[functions.chat]
verify_jwt = false

[functions.chat-bedrock]
verify_jwt = false

[functions.generate-email]
verify_jwt = true

[functions.send-emails]
verify_jwt = true